// Bảng dữ liệu Can Chi, Ngũ Hành Nạp Âm Lục Thập Hoa Giáp và Bát Trạch Phong Thủy

// 8 cung phối 8 phương vị
export const BAGUA_DIRECTIONS_MAP = {
  'Khảm': {
    'Bắc': 'Phục Vị',
    'Đông Bắc': 'Ngũ Quỷ',
    'Đông': 'Thiên Y',
    'Đông Nam': 'Sinh Khí',
    'Nam': 'Diên Niên',
    'Tây Nam': 'Tuyệt Mệnh',
    'Tây': 'Họa Hại',
    'Tây Bắc': 'Lục Sát',
  },
  'Ly': {
    'Bắc': 'Diên Niên',
    'Đông Bắc': 'Họa Hại',
    'Đông': 'Sinh Khí',
    'Đông Nam': 'Thiên Y',
    'Nam': 'Phục Vị',
    'Tây Nam': 'Lục Sát',
    'Tây': 'Ngũ Quỷ',
    'Tây Bắc': 'Tuyệt Mệnh',
  },
  'Chấn': {
    'Bắc': 'Thiên Y',
    'Đông Bắc': 'Lục Sát',
    'Đông': 'Phục Vị',
    'Đông Nam': 'Diên Niên',
    'Nam': 'Sinh Khí',
    'Tây Nam': 'Họa Hại',
    'Tây': 'Tuyệt Mệnh',
    'Tây Bắc': 'Ngũ Quỷ',
  },
  'Tốn': {
    'Bắc': 'Sinh Khí',
    'Đông Bắc': 'Tuyệt Mệnh',
    'Đông': 'Diên Niên',
    'Đông Nam': 'Phục Vị',
    'Nam': 'Thiên Y',
    'Tây Nam': 'Ngũ Quỷ',
    'Tây': 'Lục Sát',
    'Tây Bắc': 'Họa Hại',
  },
  'Càn': {
    'Bắc': 'Lục Sát',
    'Đông Bắc': 'Thiên Y',
    'Đông': 'Ngũ Quỷ',
    'Đông Nam': 'Họa Hại',
    'Nam': 'Tuyệt Mệnh',
    'Tây Nam': 'Diên Niên',
    'Tây': 'Sinh Khí',
    'Tây Bắc': 'Phục Vị',
  },
  'Khôn': {
    'Bắc': 'Tuyệt Mệnh',
    'Đông Bắc': 'Sinh Khí',
    'Đông': 'Họa Hại',
    'Đông Nam': 'Ngũ Quỷ',
    'Nam': 'Lục Sát',
    'Tây Nam': 'Phục Vị',
    'Tây': 'Thiên Y',
    'Tây Bắc': 'Diên Niên',
  },
  'Cấn': {
    'Bắc': 'Ngũ Quỷ',
    'Đông Bắc': 'Phục Vị',
    'Đông': 'Lục Sát',
    'Đông Nam': 'Tuyệt Mệnh',
    'Nam': 'Họa Hại',
    'Tây Nam': 'Sinh Khí',
    'Tây': 'Diên Niên',
    'Tây Bắc': 'Thiên Y',
  },
  'Đoài': {
    'Bắc': 'Họa Hại',
    'Đông Bắc': 'Diên Niên',
    'Đông': 'Tuyệt Mệnh',
    'Đông Nam': 'Lục Sát',
    'Nam': 'Ngũ Quỷ',
    'Tây Nam': 'Thiên Y',
    'Tây': 'Phục Vị',
    'Tây Bắc': 'Sinh Khí',
  },
};

// Chi tiết 8 sao Bát Trạch
export const STAR_INFO = {
  'Sinh Khí': {
    type: 'Cát',
    alias: 'Tham Lang Tinh',
    element: 'Mộc',
    score: 10,
    badgeColor: '#10B981',
    summary: 'Đại cát - Thu hút tài lộc, vinh hoa phú quý, thăng quan tiến chức',
    fullDesc: 'Sinh Khí là cung tốt nhất trong Bát Trạch. Đem lại tài vận hanh thông, kinh doanh phát đạt, sức khỏe dồi dào, con cái thông minh giỏi giang. Thích hợp nhất đặt cửa chính, phòng khách, phòng làm việc.',
  },
  'Thiên Y': {
    type: 'Cát',
    alias: 'Cự Môn Tinh',
    element: 'Thổ',
    score: 9.5,
    badgeColor: '#059669',
    summary: 'Đại cát - Sức khỏe dồi dào, trường thọ, gặp quý nhân phù trợ',
    fullDesc: 'Thiên Y chủ về sức khỏe và sự trường thọ, tiêu trừ ốm đau bệnh tật, tâm tính an hòa. Đây là hướng rất tốt để đặt phòng ngủ hoặc bàn thờ, giúp gia đạo bình an, gặp dữ hóa lành.',
  },
  'Diên Niên': {
    type: 'Cát',
    alias: 'Vũ Khúc Tinh',
    element: 'Kim',
    score: 9,
    badgeColor: '#0284C7',
    summary: 'Thứ cát - Gia đạo hòa thuận, tình cảm vợ chồng son sắt, bền vững',
    fullDesc: 'Diên Niên (hay Phúc Đức) củng cố các mối quan hệ tình cảm trong gia đình, vợ chồng hòa thuận, con cái hiếu thảo, ngoại giao bạn bè tốt đẹp. Rất thích hợp đặt hướng cửa phòng ngủ hoặc phòng khách.',
  },
  'Phục Vị': {
    type: 'Cát',
    alias: 'Tả Phù Tinh',
    element: 'Mộc',
    score: 8.5,
    badgeColor: '#6366F1',
    summary: 'Tiểu cát - Bình yên, tĩnh tâm, thi cử đỗ đạt, công danh thuận lợi',
    fullDesc: 'Phục Vị mang lại sự bình an nội tâm, củng cố ý chí và sức mạnh tinh thần. Hướng này rất tốt cho việc học tập, thi cử, nơi yên tĩnh để làm việc, đặt bàn thờ hoặc phòng đọc sách.',
  },
  'Tuyệt Mệnh': {
    type: 'Hung',
    alias: 'Phá Quân Tinh',
    element: 'Kim',
    score: 1,
    badgeColor: '#DC2626',
    summary: 'Đại hung - Tổn hao sức khỏe, tài sản tiêu tán, tai ương hiểm họa',
    fullDesc: 'Tuyệt Mệnh là cung hung hiểm nhất. Có thể gây bệnh tật dai dẳng, hao tài phá sản, bất hòa trầm trọng. Tuyệt đối không mở cửa chính hay đặt ban thờ tại đây.',
    cures: 'Hóa giải: Dùng nguyên tắc "Đa cát thắng tiểu hung". Bố trí bếp tọa Tuyệt Mệnh hướng Sinh Khí/Thiên Y để thiêu đốt hung khí. Đặt gương Bát Quái lồi trấn yểm hoặc dùng vật phẩm hành Thủy (Thủy làm suy yếu Kim của Tuyệt Mệnh).',
  },
  'Ngũ Quỷ': {
    type: 'Hung',
    alias: 'Liêm Trinh Tinh',
    element: 'Hỏa',
    score: 2,
    badgeColor: '#EA580C',
    summary: 'Đại hung - Mất mát của cải, dễ gặp thị phi, hỏa hoạn, tiểu nhân quấy phá',
    fullDesc: 'Ngũ Quỷ chủ về hỏa tai, mất trộm, tranh chấp kiện tụng, sức khỏe suy giảm, tinh thần bất an. Tránh đặt cửa chính và phòng ngủ.',
    cures: 'Hóa giải: Bố trí bếp tọa Ngũ Quỷ hướng Sinh Khí. Sử dụng vật phẩm ngũ hành Thủy để dập tắt hỏa tính của Liêm Trinh, hoặc gương Bát Quái trấn cửa.',
  },
  'Lục Sát': {
    type: 'Hung',
    alias: 'Văn Khúc Tinh',
    element: 'Thủy',
    score: 3,
    badgeColor: '#D97706',
    summary: 'Thứ hung - Tình cảm trục trặc, kiện tụng tranh chấp, hao tài tốn của',
    fullDesc: 'Lục Sát mang sát khí về quan hệ gia đình xáo trộn, đào hoa xấu hại thân, công việc bị cản trở, dễ dính líu đến kiện cáo.',
    cures: 'Hóa giải: Đặt nhà vệ sinh, kho bãi hoặc bếp tọa Lục Sát để triệt tiêu sát khí. Sử dụng vật phẩm hành Thổ (bình gốm, thạch anh vàng) để khắc chế Thủy của Lục Sát.',
  },
  'Họa Hại': {
    type: 'Hung',
    alias: 'Lộc Tồn Tinh',
    element: 'Thổ',
    score: 4,
    badgeColor: '#B45309',
    summary: 'Thứ hung - Gặp chuyện không may, thất bại hao tổn, bất hòa gia đạo',
    fullDesc: 'Họa Hại gây nên nhiều trắc trở vụn vặt, mâu thuẫn lời qua tiếng lại, việc làm không thành, dễ làm nản lòng gia chủ.',
    cures: 'Hóa giải: Bố trí bếp hoặc nhà kho tọa Họa Hại. Dùng vật phẩm hành Kim (chuông gió đồng, tượng kim loại) để tiết chế Thổ khí xấu của Lộc Tồn.',
  },
};

// Chi tiết 8 hướng địa lý và góc độ
export const DIRECTIONS_LIST = [
  { direction: 'Bắc', angleRange: '337.5° - 22.5°', degreesCenter: 0, bagua: 'Khảm', element: 'Thủy' },
  { direction: 'Đông Bắc', angleRange: '22.5° - 67.5°', degreesCenter: 45, bagua: 'Cấn', element: 'Thổ' },
  { direction: 'Đông', angleRange: '67.5° - 112.5°', degreesCenter: 90, bagua: 'Chấn', element: 'Mộc' },
  { direction: 'Đông Nam', angleRange: '112.5° - 157.5°', degreesCenter: 135, bagua: 'Tốn', element: 'Mộc' },
  { direction: 'Nam', angleRange: '157.5° - 202.5°', degreesCenter: 180, bagua: 'Ly', element: 'Hỏa' },
  { direction: 'Tây Nam', angleRange: '202.5° - 247.5°', degreesCenter: 225, bagua: 'Khôn', element: 'Thổ' },
  { direction: 'Tây', angleRange: '247.5° - 292.5°', degreesCenter: 270, bagua: 'Đoài', element: 'Kim' },
  { direction: 'Tây Bắc', angleRange: '292.5° - 337.5°', degreesCenter: 315, bagua: 'Càn', element: 'Kim' },
];

export const FIVE_ELEMENTS_RELATION = {
  'Kim': {
    color: '#E2E8F0',
    generates: 'Thủy',
    generatedBy: 'Thổ',
    overcomes: 'Mộc',
    overcomeBy: 'Hỏa',
    colors: ['Trắng', 'Xám', 'Ghi', 'Vàng ánh kim', 'Nâu đất', 'Vàng sậm'],
    luckyStone: 'Thạch anh trắng, Đá mắt hổ vàng nâu, Moonstone',
  },
  'Mộc': {
    color: '#10B981',
    generates: 'Hỏa',
    generatedBy: 'Thủy',
    overcomes: 'Thổ',
    overcomeBy: 'Kim',
    colors: ['Xanh lá cây', 'Xanh nõn chuối', 'Đen', 'Xanh nước biển'],
    luckyStone: 'Ngọc bích Nephrite, Thạch anh xanh Aventurine, Cẩm thạch',
  },
  'Thủy': {
    color: '#06B6D4',
    generates: 'Mộc',
    generatedBy: 'Kim',
    overcomes: 'Hỏa',
    overcomeBy: 'Thổ',
    colors: ['Đen', 'Xanh dương thẫm', 'Trắng', 'Xám bạc'],
    luckyStone: 'Thạch anh đen, Đá Aquamarine, Đá Obsidian đen',
  },
  'Hỏa': {
    color: '#EF4444',
    generates: 'Thổ',
    generatedBy: 'Mộc',
    overcomes: 'Kim',
    overcomeBy: 'Thủy',
    colors: ['Đỏ', 'Hồng', 'Tím', 'Cam', 'Xanh lá cây'],
    luckyStone: 'Thạch anh tóc đỏ, Ruby tự nhiên, Thạch anh tím Amethyst',
  },
  'Thổ': {
    color: '#F59E0B',
    generates: 'Kim',
    generatedBy: 'Hỏa',
    overcomes: 'Thủy',
    overcomeBy: 'Mộc',
    colors: ['Vàng', 'Nâu đất', 'Đỏ', 'Hồng', 'Tím'],
    luckyStone: 'Thạch anh vàng Citrine, Đá mắt hổ vàng, Hổ phách',
  },
};

export const THREE_HARMONIES = [
  ['Thân', 'Tý', 'Thìn'],
  ['Tỵ', 'Dậu', 'Sửu'],
  ['Dần', 'Ngọ', 'Tuất'],
  ['Hợi', 'Mão', 'Mùi'],
];

export const SIX_HARMONIES = [
  ['Tý', 'Sửu'],
  ['Dần', 'Hợi'],
  ['Mão', 'Tuất'],
  ['Thìn', 'Dậu'],
  ['Tỵ', 'Thân'],
  ['Ngọ', 'Mùi'],
];

export const SIX_CLASHES = [
  ['Tý', 'Ngọ'],
  ['Sửu', 'Mùi'],
  ['Dần', 'Thân'],
  ['Mão', 'Dậu'],
  ['Thìn', 'Tuất'],
  ['Tỵ', 'Hợi'],
];

export const SIX_HARMS = [
  ['Tý', 'Mùi'],
  ['Sửu', 'Ngọ'],
  ['Dần', 'Tỵ'],
  ['Mão', 'Thìn'],
  ['Thân', 'Hợi'],
  ['Dậu', 'Tuất'],
];

export const CAN_HARMONIES = [
  ['Giáp', 'Kỷ'],
  ['Ất', 'Canh'],
  ['Bính', 'Tân'],
  ['Đinh', 'Nhâm'],
  ['Mậu', 'Quý'],
];

export const CAN_CLASHES = [
  ['Giáp', 'Canh'],
  ['Ất', 'Tân'],
  ['Bính', 'Nhâm'],
  ['Đinh', 'Quý'],
  ['Mậu', 'Giáp'],
  ['Kỷ', 'Ất'],
  ['Canh', 'Bính'],
  ['Tân', 'Đinh'],
  ['Nhâm', 'Mậu'],
  ['Quý', 'Kỷ'],
];

export const SPOUSE_CUNG_MAP = {
  'Khảm': {
    'Khảm': 'Phục Vị',
    'Chấn': 'Thiên Y',
    'Tốn': 'Sinh Khí',
    'Ly': 'Diên Niên',
    'Khôn': 'Tuyệt Mệnh',
    'Đoài': 'Họa Hại',
    'Càn': 'Lục Sát',
    'Cấn': 'Ngũ Quỷ',
  },
  'Chấn': {
    'Khảm': 'Thiên Y',
    'Chấn': 'Phục Vị',
    'Tốn': 'Diên Niên',
    'Ly': 'Sinh Khí',
    'Khôn': 'Họa Hại',
    'Đoài': 'Tuyệt Mệnh',
    'Càn': 'Ngũ Quỷ',
    'Cấn': 'Lục Sát',
  },
  'Tốn': {
    'Khảm': 'Sinh Khí',
    'Chấn': 'Diên Niên',
    'Tốn': 'Phục Vị',
    'Ly': 'Thiên Y',
    'Khôn': 'Ngũ Quỷ',
    'Đoài': 'Lục Sát',
    'Càn': 'Họa Hại',
    'Cấn': 'Tuyệt Mệnh',
  },
  'Ly': {
    'Khảm': 'Diên Niên',
    'Chấn': 'Sinh Khí',
    'Tốn': 'Thiên Y',
    'Ly': 'Phục Vị',
    'Khôn': 'Lục Sát',
    'Đoài': 'Ngũ Quỷ',
    'Càn': 'Tuyệt Mệnh',
    'Cấn': 'Họa Hại',
  },
  'Càn': {
    'Khảm': 'Lục Sát',
    'Chấn': 'Ngũ Quỷ',
    'Tốn': 'Họa Hại',
    'Ly': 'Tuyệt Mệnh',
    'Khôn': 'Diên Niên',
    'Đoài': 'Sinh Khí',
    'Càn': 'Phục Vị',
    'Cấn': 'Thiên Y',
  },
  'Khôn': {
    'Khảm': 'Tuyệt Mệnh',
    'Chấn': 'Họa Hại',
    'Tốn': 'Ngũ Quỷ',
    'Ly': 'Lục Sát',
    'Khôn': 'Phục Vị',
    'Đoài': 'Thiên Y',
    'Càn': 'Diên Niên',
    'Cấn': 'Sinh Khí',
  },
  'Cấn': {
    'Khảm': 'Ngũ Quỷ',
    'Chấn': 'Lục Sát',
    'Tốn': 'Tuyệt Mệnh',
    'Ly': 'Họa Hại',
    'Khôn': 'Sinh Khí',
    'Đoài': 'Diên Niên',
    'Càn': 'Thiên Y',
    'Cấn': 'Phục Vị',
  },
  'Đoài': {
    'Khảm': 'Họa Hại',
    'Chấn': 'Tuyệt Mệnh',
    'Tốn': 'Lục Sát',
    'Ly': 'Ngũ Quỷ',
    'Khôn': 'Thiên Y',
    'Đoài': 'Phục Vị',
    'Càn': 'Sinh Khí',
    'Cấn': 'Diên Niên',
  },
};
